import additionalNumber from './modules/additionalNumber';
import toggleMenu from './modules/toggleMenu';
import allServicesPopup from './modules/allServicesPopup';
import phoneMask from './modules/phoneMask';
import sendForm from './modules/sendForm';
import consultations from './modules/consultaions';
import closePopups from './modules/closePopups';
import faq from './modules/faq';
import hintsDesktop from './modules/hintsDesktop';
import hintsMobile from './modules/hintsMobile';
import sliderWTabs from './modules/sliderWTabs';
import sliderWithoutTabs from './modules/sliderWithoutTabs';

closePopups();
additionalNumber();
toggleMenu();
allServicesPopup();
phoneMask();
sendForm();
consultations();
faq();
hintsDesktop();
hintsMobile();
sliderWTabs();
sliderWithoutTabs();
